[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
zkevm = "${ZKEVM_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
optimism-sepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${BASE_ETHERSCAN_API_KEY}" }
